### ISSUE TITLE
Wazuh-install.sh fails when installing only the manager

### ISSUE THREAD

**Issue by jseg380** [wazuh/wazuh-installation-assistant#128]
## Description  
Using the [4.10.x wazuh-install.sh script](https://packages-dev.wazuh.com/4.10/wazuh-install.sh) to exclusively install the manager fails because filebeat tries to test its connection with the indexer even though it is not installed.

Error:
```
04/11/2024 09:12:11 INFO: Filebeat post-install configuration finished.
Successfully updated the keystore
Successfully updated the keystore
04/11/2024 09:12:12 INFO: The filebeat.yml file has been updated to use the Filebeat Keystore username and password.
04/11/2024 09:12:32 INFO: Starting service filebeat.
Created symlink from /etc/systemd/system/multi-user.target.wants/filebeat.service to /usr/lib/systemd/system/filebeat.service.
04/11/2024 09:12:32 INFO: filebeat service started.
04/11/2024 09:12:32 INFO: Checking Filebeat connection
04/11/2024 09:12:32 ERROR: Filebeat connection Error.
elasticsearch: https://x.x.x.x:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: x.x.x.x
    dial up... ERROR dial tcp x.x.x.x:9200: connect: connection refused

04/11/2024 09:12:32 INFO: --- Removing existing Wazuh installation ---
04/11/2024 09:12:32 INFO: Removing Wazuh manager.
```

Call to the script: 
`bash wazuh-install.sh --wazuh-server {node_name} --ignore-check -d pre-release`

Attachments: [wazuh-install.log](https://github.com/user-attachments/files/17617476/wazuh-install.log)

## Task

- [ ] Allow for the use of wazuh-install.sh 4.10 to install only the manager.

**Comment by teddytpc1** [comment]
The Installation assistant is intended to be used as part of a complete Wazuh installation. By following the installation guide, the Wazuh indexer should be installed before the Wazuh manager.
This behavior is expected.

**Comment by teddytpc1** [comment]
This will be fixed by reverting the changes of [this PR](https://github.com/wazuh/wazuh-packages/pull/3059).
- https://github.com/wazuh/wazuh-installation-assistant/issues/137
