### ISSUE TITLE
Installation assistant code and pipelines migration

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-installation-assistant#21]
| Objective |
|---|
| https://github.com/wazuh/wazuh-packages/issues/2904 | 

## Description
Because of the `Wazuh packages redesign tier 2` objective we need to migrate the Wazuh installation assistant-related files and pipelines.

## Issues
- https://github.com/wazuh/wazuh-installation-assistant/issues/19
- https://github.com/wazuh/wazuh-installation-assistant/issues/20
- https://github.com/wazuh/wazuh-installation-assistant/issues/51
- https://github.com/wazuh/wazuh-installation-assistant/issues/41
- https://github.com/wazuh/wazuh-installation-assistant/issues/55
- https://github.com/wazuh/wazuh-installation-assistant/issues/62
- https://github.com/wazuh/wazuh-installation-assistant/issues/63

**Comment by davidcr01** [comment]
## Summary

- PR to migrate all the Wazuh installation assistant code without changes: https://github.com/wazuh/wazuh-installation-assistant/pull/31

**Comment by c-bordon** [comment]
The necessary changes were made, all tasks were completed.
