### ISSUE TITLE
Generate final tag and publish draft release for Wazuh 4.9.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-installation-assistant#48]
## Description

This issue attempts to publish draft release and generate final tag for version 4.9.0 in the wazuh-installation-assistant repository.

## Tasks

- [ ] Generate final tag v4.9.0 from branch 4.9.0 on wazuh-installation-assistant repository.
- [ ] Publish [GitHub draft release](https://github.com/wazuh/wazuh-installation-assistant/releases) from [tag v4.9.0](https://github.com/wazuh/wazuh-installation-assistant/tree/v4.9.0).

**Comment by davidcr01** [comment]
This repo will not be used until 4.10.0 version.
