### ISSUE TITLE
Consider to increase the `wazuh-cert-tool.sh` RSA-2048 and SHA-256 to 4096 and 512

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-installation-assistant#6]
The Wazuh certificates creation tool uses the cipher algorithms RSA 2048 and SHA 256. It's time to analyze if we can upgrade them to 4096 and 512 respectively.

**Comment by sebasfalcone** [comment]
## Manager side

The only impact that comes to mind is that the Keystore did not support certificates other than [RSA-2048](https://github.com/wazuh/wazuh/issues/24111). However, we no longer use certificates starting from version [4.8.1](https://github.com/wazuh/wazuh/issues/24509)

I do not foresee any issues since these changes are included in version `4.10.0`.

**Comment by c-bordon** [comment]
wazuh-packages branch with the changes: https://github.com/wazuh/wazuh-packages/tree/feature/1922-consider-to-increase-the-wazuh-cert-toolsh-rsa-2048-and-sha-256-to-4096-and-512

**Comment by CarlosALgit** [comment]
## Update Report
We have to also change this command:

```
openssl req -new -nodes -newkey rsa:2048 -keyout ${cert_tmp_path}/${server_name}-key.pem -out ${cert_tmp_path}/${server_name}.csr  -config ${cert_tmp_path}/${server_name}.conf
```

In order to assure the certificates are changed to `RSA-4096`.

There are more commands similar to this one we have to change and test in order to include `SHA-512` too.

**Comment by CarlosALgit** [comment]
## Update Report
I've been researching through the AIO installation I did with the new certificates looking for problems with the certificates. I've activated debug mode but did not find anything out of the ordinary. I'll keep investigating this with the help of my team.

**Comment by teddytpc1** [comment]
Moved to 5.0.0 as part of the DevOps overhaul.

**Comment by teddytpc1** [comment]
This will be closed as not planned.
