### ISSUE TITLE
Update the Wazuh installation assistant to support revision number

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-installation-assistant#62]
related: https://github.com/wazuh/wazuh-installation-assistant/issues/21

With the changes required for tier 2 redistribution packages, we must modify the installation assistant to contain the revision number within its code.

To do this it is necessary to modify the variable `wazuh_install_vesion` to `wazuh_install_revision`

https://github.com/wazuh/wazuh-installation-assistant/blob/0e5b6066a46471f4715b8809cd604f19e723c3b4/install_functions/installVariables.sh#L13

It is also necessary to update the message so that it contains version and revision

https://github.com/wazuh/wazuh-installation-assistant/blob/0e5b6066a46471f4715b8809cd604f19e723c3b4/install_functions/installMain.sh#L216

**Comment by davidcr01** [comment]
# Update Report

## Development

After the change, the Installation assistant returns the correct revision number.

```console
➜  wazuh-installation-assistant git:(change/62-add-support-revision-number) ✗ sudo bash wazuh-install.sh -V 
18/09/2024 12:26:12 INFO: Wazuh version: 4.10.0
18/09/2024 12:26:12 INFO: Filebeat version: 7.10.2
18/09/2024 12:26:12 INFO: Wazuh installation assistant revision: 1
```

**Comment by c-bordon** [comment]
This change will not be applied to 4.10.0 version, we will resume this task in 5.0.0
