### ISSUE TITLE
The Wazuh API user wazuh does not exist and The Wazuh API user wazuh-wui does not exist

### ISSUE THREAD

**Issue by fuuussiiidiel** [wazuh/wazuh-installation-assistant#66]
|4.8.0|wazuh server|assisted installation|assisted installation|Ubuntu 24.04|

When performing the assisted installation (all components on the same machine)
on my fresh Ubuntu 24.04,
at the stage of wazuh server (wazuh-manager), I receive this error:

15/07/2024 12:27:17 ERROR: The Wazuh API user wazuh does not exist
15/07/2024 12:27:17 ERROR: The Wazuh API user wazuh-wui does not exist
15/07/2024 12:28:57 INFO: Starting service filebeat.

But the installation is successfull.
But still when trying to access the dashboard, "Wazuh API seems to be down".

![image](https://github.com/user-attachments/assets/8e285e5d-d182-4dcb-ab3b-595a301283c2)

Details from:
https://github.com/wazuh/wazuh/issues/24587

Any solution for this issue or a workaround?

**Comment by davidcr01** [comment]
I am closing this issue as not planned and this will be discussed in https://github.com/wazuh/wazuh/issues/24587 for better visibility.
